<?php

namespace Ais\WisudaBundle\Repository;

/**
 * WisudaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WisudaRepository extends \Doctrine\ORM\EntityRepository
{
}
